### ISSUE TITLE
npm-windows-upgrade

### ISSUE THREAD

**Issue by cscaushik** [felixrieseberg/npm-windows-upgrade#103]
Hi Team,

I am trying upgrade npm to version 3.10.8.
Followed the steps on the link https://github.com/felixrieseberg/npm-windows-upgrade.

When I try to execute the following step, I get an error
PS C:\Program Files\nodejs> npm-windows-upgrade
npm-windows-upgrade v3.1.1
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn powershell.exe ENOENT
    at exports._errnoException (util.js:1036:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

Could you please help me resolve this issue.

**Comment by gangadharjannu** [comment]
as suggested by @s-limo, try below:

Please check if your powershell is in PATH. Solution could be run the following command (or update system PATH variable) before running npm-windows-upgrade
c:> set path=%path%;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\
