### ISSUE TITLE
Error: Cannot find module 'cli-cursor'

### ISSUE THREAD

**Issue by PGorshkov** [felixrieseberg/npm-windows-upgrade#127]
Hey. After the update starts, it shows that it does not find the cli-cursor module. Help me :(
`Error: Cannot find module 'cli-cursor'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\1\AppData\Roaming\npm\node_modules\npm-windows-upgrade\node_modules\inquirer\lib\pro
mpts\list.js:9:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)`

**Comment by felixrieseberg** [comment]
I believe that your installation is corrupt. Could you try installing `npm-windows-upgrade` again?
