### ISSUE TITLE
failed to upgrade

### ISSUE THREAD

**Issue by a-wip0** [felixrieseberg/npm-windows-upgrade#144]
```
npm-windows-upgrade v6.0.1
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn powershell.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

I got this error when try to upgrading 
my node version is 10.15.3 and
my npm version is 6.4.1

My windows version is
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      17763  0

**Comment by kptlronyttcna** [comment]
Same issue
