### ISSUE TITLE
Cannot install latest version on Windows

### ISSUE THREAD

**Issue by gabrielw007** [felixrieseberg/npm-windows-upgrade#178]
You wanted to install npm 7.20.3, but we could not confirm that the installation succeeded.
Please consider reporting your trouble to https://aka.ms/npm-issues.

Debug Information:

node: 14.17.4 | v8: 8.4.371.23-node.76 | uv: 1.41.0 | zlib: 1.2.11 | brotli: 1.0.9 | ares: 1.17.1 | modules: 83 | nghttp2: 1.42.0 | napi: 8 | llhttp: 2.1.3 | openssl: 1.1.1k | cldr: 39.0 | icu: 69.1 | tz: 2021a | unicode: 13.0 | os: win32 x64 | OS Name: Microsoft Windows 10 Pro
OS Version: 10.0.17763 N/A Build 17763

also after that it fails to run again in the same folder i ran it before: 

npm-windows-upgrade
npm-windows-upgrade v6.0.1
undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at C:\Users\gabrielw\AppData\Roaming\npm\node_modules\npm-windows-upgrade\src\versions.js:36:20
    at ChildProcess.exithandler (child_process.js:381:7)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)

also it fails to show npm version:

npm --version
(node:39116) UnhandledPromiseRejectionWarning: Error: Cannot find module 'is-fullwidth-code-point'
Require stack:
- C:\Program Files\nodejs\node_modules\npm\node_modules\string-width\index.js
- C:\Program Files\nodejs\node_modules\npm\node_modules\wide-align\align.js
- C:\Program Files\nodejs\node_modules\npm\node_modules\gauge\render-template.js
- C:\Program Files\nodejs\node_modules\npm\node_modules\gauge\plumbing.js
- C:\Program Files\nodejs\node_modules\npm\node_modules\gauge\index.js
- C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\log.js
- C:\Program Files\nodejs\node_modules\npm\lib\cli.js
- C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\string-width\index.js:3:30)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:39116) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:39116) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:23520) UnhandledPromiseRejectionWarning: Error: Cannot find module 'is-fullwidth-code-point'
Require stack:
- C:\Program Files\nodejs\node_modules\npm\node_modules\string-width\index.js
- C:\Program Files\nodejs\node_modules\npm\node_modules\wide-align\align.js
- C:\Program Files\nodejs\node_modules\npm\node_modules\gauge\render-template.js
- C:\Program Files\nodejs\node_modules\npm\node_modules\gauge\plumbing.js
- C:\Program Files\nodejs\node_modules\npm\node_modules\gauge\index.js
- C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\log.js
- C:\Program Files\nodejs\node_modules\npm\lib\cli.js
- C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\string-width\index.js:3:30)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:23520) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23520) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by gabrielw007** [comment]
after i removed npm files from C:\Program Files\nodejs folder and changed my folder from project's one to c:\windows\system32 it did work!
