### ISSUE TITLE
Unexpected token p

### ISSUE THREAD

**Issue by Faleij** [felixrieseberg/npm-windows-upgrade#22]
might be related to #15 and #13
```
PS C:\WINDOWS\system32> Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force
PS C:\WINDOWS\system32> node -v
v0.12.7
PS C:\WINDOWS\system32> npm -v
2.11.3
PS C:\WINDOWS\system32> npm-windows-upgrade
npm-windows-upgrade 0.2.10
? This tool will upgrade npm. Do you want to continue? Yes
undefined:1
npm command view
 ^
SyntaxError: Unexpected token p
    at Object.parse (native)
    at C:\Users\falei\AppData\Roaming\npm\node_modules\npm-windows-upgrade\bin\npm-windows-upgrade:73:17
    at ChildProcess.exithandler (child_process.js:742:7)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
PS C:\WINDOWS\system32> 
PS C:\WINDOWS\system32> npm-windows-upgrade --version:3.1.0
npm-windows-upgrade 0.2.10
? This tool will upgrade npm. Do you want to continue? Yes
Upgrading.. -Error:  Join-Path : Cannot find drive. A drive with the name 'npm command configC' does not exist.

Error:  At C:\Users\falei\AppData\Roaming\npm\node_modules\npm-windows-upgrade\powershell\upgrade-npm.ps1:103 char:20
+ $AssumedNpmPath = (Join-Path $NodePath "node_modules\npm")
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (npm command configC:String) [Join-Path], DriveNotFoundException
    + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.JoinPathCommand




You wanted to install npm 3.1.0, but the installed version is2.11.3.
Please consider reporting your trouble to http://aka.ms/npm-issues.
Here is the output from the upgrader script:
[] [ 'Join-Path : Cannot find drive. A drive with the name \'npm command configC\' does not exist.\r\n',
  'At C:\\Users\\falei\\AppData\\Roaming\\npm\\node_modules\\npm-windows-upgrade\\powershell\\upgrade-npm.ps1:103 char:2
0\r\n+ $AssumedNpmPath = (Join-Path $NodePath "node_modules\\npm")\r\n+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~\r\n    + CategoryInfo          : ObjectNotFound: (npm command configC:String) [Join-Path], DriveNotFoundExcept
ion\r\n    + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.JoinPathCommand\r\n \r\n' ]
```

**Comment by Faleij** [comment]
uninstalled using latest nodejs installer and reinstalled with nodejs installer which gave me npm 2.13.2 and then it just worked.
