### ISSUE TITLE
Error using npm-windows-upgrade

### ISSUE THREAD

**Issue by borinvidal** [felixrieseberg/npm-windows-upgrade#29]
PS C:\WINDOWS\system32> npm-windows-upgrade
npm-windows-upgrade 0.4.0
? This tool will upgrade npm. Do you want to continue? Yes
? Which version do you want to install? 3.3.0
Upgrading.. |Error:  npm
Error:
Error:  http GET https://registry.npmjs.org/npm/3.3.0

Upgrading.. |Error:  npm
Error:
Error:  http
Error:  200 https://registry.npmjs.org/npm/3.3.0

Upgrading.. /Error:  npm
Error:
Error:  http
Error:   GET https://registry.npmjs.org/npm/-/npm-3.3.0.tgz

Upgrading.. -Error:  npm
Error:
Error:  http
Error:   200 https://registry.npmjs.org/npm/-/npm-3.3.0.tgz

Upgrading.. -

Could not determine npm version.
You wanted to install npm 3.3.0, but the installed version isnull.
Please consider reporting your trouble to http://aka.ms/npm-issues.
Here is the output from the upgrader script:
[ '\r\n',
  '\r\n',
  '    Directorio: C:\\Users\\svidal\\AppData\\Local\\Temp\r\n',
  '\r\n\r\n',
  'Mode                LastWriteTime     Length Name
  \r\n',
  '----                -------------     ------ ----
  \r\n',
  'd----        20/08/2015     10:11            npm_upgrade
  \r\n',
  'npm@3.3.0 node_modules\\npm\n',
  'All done!\r\n',
  '\r\n',
  '\r\n' ] [ 'npm',
  ' ',
  'http GET https://registry.npmjs.org/npm/3.3.0\n',
  'npm',
  ' ',
  'http ',
  '200 https://registry.npmjs.org/npm/3.3.0\n',
  'npm',
  ' ',
  'http',
  ' GET https://registry.npmjs.org/npm/-/npm-3.3.0.tgz\n',
  'npm',
  ' ',
  'http',
  ' 200 https://registry.npmjs.org/npm/-/npm-3.3.0.tgz\n' ]
PS C:\WINDOWS\system32> npm -v

module.js:340
    throw err;
          ^
Error: Cannot find module 'are-we-there-yet'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npmlog\log.js:2:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
PS C:\WINDOWS\system32> npm-windows-upgrade
npm-windows-upgrade 0.4.0
? This tool will upgrade npm. Do you want to continue? Yes
We could not show latest available versions. Try running this script again with the version you want to install (npm-win
dows-upgrade --version:3.0.0
PS C:\WINDOWS\system32> npm-windows-upgrade --version:3.1.0
npm-windows-upgrade 0.4.0
? This tool will upgrade npm. Do you want to continue? Yes
Upgrading.. |Error:
module.js:340
    throw err;
          ^
Error: Cannot find module 'are-we-there-yet'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npmlog\log.js:2:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

Upgrading.. /

Could not determine npm version.
You wanted to install npm 3.1.0, but the installed version isnull.
Please consider reporting your trouble to http://aka.ms/npm-issues.
Here is the output from the upgrader script:
[ 'All done!\r\n' ] [ '\r\nmodule.js:340\r\n    throw err;\r\n          ^\r\nError: Cannot find module \'are-we-there-ye
t\'\r\n    at Function.Module._resolveFilename (module.js:338:15)\r\n    at Function.Module._load (module.js:280:25)\r\n
    at Module.require (module.js:364:17)\r\n    at require (module.js:380:17)\r\n    at Object.<anonymous> (C:\\Program
Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\npmlog\\log.js:2:16)\r\n    at Module._compile (module.js:456:26)\
r\n    at Object.Module._extensions..js (module.js:474:10)\r\n    at Module.load (module.js:356:32)\r\n    at Function.M
odule._load (module.js:312:12)\r\n    at Module.require (module.js:364:17)\r\n' ]

**Comment by borinvidal** [comment]
Windows 8.1

**Comment by felixrieseberg** [comment]
Hey, thanks for reporting, sorry to see that you're having trouble - I can tell from the first few lines of output that your computes had trouble getting the new npm bits, but npm still attempted an upgrade - and kind of shot itself in the foot.

You can fix this by running the official Node.js installer and this script again.

**Comment by borinvidal** [comment]
OK.
Thanks.

2015-08-20 17:09 GMT+02:00 Felix Rieseberg <notifications@github.com>:
