### ISSUE TITLE
Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by MhSaadany** [felixrieseberg/npm-windows-upgrade#5]
```
npm-windows-upgrade
npm-upgrade-windows 0.1.5
? This tool will upgrade npm. Do you want to continue? Yes
? Which version do you want to install? 2.12.1
Upgrading.. -

npm-windows-upgrade\bin\npm-windows-upgrade:65
        } else if (output[output.length].indexOf('All done!') > -1) {
                                        ^
TypeError: Cannot read property 'indexOf' of undefined
    at C:\Users\User\AppData\Roaming\npm\node_modules\npm-windows-upgrade\bin\npm-windows-upgrade:65:41
    at ChildProcess.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\npm-windows-upgrade\bin\npm-windows-upgrade:29:9)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
```
I get this error after the elevated power-shell window is spawned. The upgrade finished successfully though and I confirmed it with `npm version`

**Comment by felixrieseberg** [comment]
Thanks! Fixed in https://github.com/felixrieseberg/npm-windows-upgrade/commit/2daf58a1238d2467ef97fbcb8735b691e89cc7a8
