### ISSUE TITLE
Upgrade fails because it doesn't respect `npm config set cafile`

### ISSUE THREAD

**Issue by klauern** [felixrieseberg/npm-windows-upgrade#55]
I have a corporate proxy that overrides certificates.  For most things, this is an easy fix, as I just provide a [`cafile` config](https://docs.npmjs.com/misc/config#cafile).

However, this tool doesn't respect that setting, as shown in this output:

```sh
C:\Users\A03182
λ npm-windows-upgrade
npm-windows-upgrade 1.2.0
? This tool will upgrade npm. Do you want to continue? Yes
? Which version do you want to install? 3.5.4
Upgrading... /Error:  npm
Error:   ERR!
Error:  fetch failed https://registry.npmjs.org/npm/-/npm-3.5.4.tgz

Error:  npm
Error:
Error:  WARN retry will retry, error on last attempt: Error: self signed certificate in certificate chain

Upgrading... /Error:  npm
Error:   ERR! fetch failed https://registry.npmjs.org/npm/-/npm-3.5.4.tgz

Error:  npm WARN retry will retry, error on last attempt: Error: self signed certificate in certificate chain

Upgrading... \Error:  npm ERR! fetch failed https://registry.npmjs.org/npm/-/npm-3.5.4.tgz

Error:  npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "npm@3.5.4"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN

npm ERR! self signed certificate in certificate chain
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

Error:
npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\nodejs\npm-debug.log

Upgrading... -

Upgrading (fallback method)... |You wanted to install npm 3.5.4, but the installed version is3.3.12.
Please consider reporting your trouble to http://aka.ms/npm-issues.

```
![image](https://cloud.githubusercontent.com/assets/4735/12329062/1487e880-baa4-11e5-8513-1e29ea31a8ac.png)

**Comment by felixrieseberg** [comment]
Hey, thanks for reporting! This is interesting, because we're still calling `npm install npm` to actually install the new version. I assume your configuration would work with any other npm install command?

**Comment by klauern** [comment]
I think so.  I had to have the `cafile` configured to install `npm-windows-upgrade`, so I figured I was all set.

**Comment by felixrieseberg** [comment]
And you should be - however, there's a bunch of ways to configure that setting. Could you do me a giant favor and try it again after setting the configuration with `npm config set --global`?

**Comment by klauern** [comment]
hm, crud.  Something went awry, now npm itself doesn't seem to be working.  Probably a separate issue:

```ps1
C:\Users\A03182
λ npm config set cafile msnroot.pem -g
module.js:329
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:20:13
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:76:3)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
 module.js:329
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:20:13
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:76:3)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
```

I might reinstall NodeJS to see if that clears things up.  Seems like most `npm` commands fail now.

**Comment by klauern** [comment]
I reinstalled Node (or really, upgraded from 5.2.0 to 5.41, and I'm going to try this again.  Not setting that globally could have been the issue.

**Comment by klauern** [comment]
Ok, I think it worked.  I don't get that error anymore, but for whatever reason, the upgrade itself had some weird errors:

```cmd
C:\Users\A03182
λ npm-windows-upgrade
npm-windows-upgrade 1.2.0
? This tool will upgrade npm. Do you want to continue? Yes
? Which version do you want to install? 3.5.4
Upgrading... |Error:  npm
Error:
Error:  WARN
Error:   ENOENT
Error:   ENOENT: no such file or directory, open 'C:\Program Files\nodejs\package.json'

Error:  npm WARN EPACKAGEJSON nodejs No description
npm WARN EPACKAGEJSON
Error:   nodejs No repository field.

Error:  npm WARN EPACKAGEJSON nodejs No README data
npm WARN EPACKAGEJSON nodejs No license field.

Upgrading... -

Upgrade finished. Your new npm version is 3.5.4. Have a nice day!
```

**Comment by felixrieseberg** [comment]
Thanks so much - you sadly encountered a bug in Node/npm (that's why you got the npmlog issues). I'm closing this for now, thanks again for reporting!
