### ISSUE TITLE
Going from 3.8.5 to 1.2.32 threw an error and killed NPM env var

### ISSUE THREAD

**Issue by TheJaredWilcurt** [felixrieseberg/npm-windows-upgrade#70]
Had to switch back to an older version. We have a repo at work that needs Node 0.10.12, so I figured I'd just set NPM to match the [version that was released at the same time](https://nodejs.org/en/download/releases/).

I got the following error.

```
C:\>npm-windows-upgrade --version:1.2.32
npm-windows-upgrade 0.3.2
? This tool will upgrade npm. Do you want to continue? Yes
Upgrading.. /Error:
C:\Users\jwilcurt\AppData\Roaming\npm\node_modules\npm\lib\npm.js:18
  var fs = gfs.gracefulify(require('fs'))
               ^
TypeError: Object #<Object> has no method 'gracefulify'
    at C:\Users\jwilcurt\AppData\Roaming\npm\node_modules\npm\lib\npm.js:18:16
    at Object.<anonymous> (C:\Users\jwilcurt\AppData\Roaming\npm\node_modules\np
m\lib\npm.js:394:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at C:\Users\jwilcurt\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js:26:
13
    at Object.<anonymous> (C:\Users\jwilcurt\AppData\Roaming\npm\node_modules\np
m\bin\npm-cli.js:76:3)

Upgrading.. -

Could not determine npm version.
You wanted to install npm 1.2.32, but the installed version isnull.
Please consider reporting your trouble to http://aka.ms/npm-issues.
Here is the output from the upgrader script:
[ 'All done!\r\n' ] [ '\r\nC:\\Users\\jwilcurt\\AppData\\Roaming\\npm\\node_modu
les\\npm\\lib\\npm.js:18\r\n  var fs = gfs.gracefulify(require(\'fs\'))\r\n
          ^\r\nTypeError: Object #<Object> has no method \'gracefulify\'\r\n
at C:\\Users\\jwilcurt\\AppData\\Roaming\\npm\\node_modules\\npm\\lib\\npm.js:18
:16\r\n    at Object.<anonymous> (C:\\Users\\jwilcurt\\AppData\\Roaming\\npm\\no
de_modules\\npm\\lib\\npm.js:394:3)\r\n    at Module._compile (module.js:456:26)
\r\n    at Object.Module._extensions..js (module.js:474:10)\r\n    at Module.loa
d (module.js:356:32)\r\n    at Function.Module._load (module.js:312:12)\r\n    a
t Module.require (module.js:364:17)\r\n    at require (module.js:380:17)\r\n
at C:\\Users\\jwilcurt\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.j
s:26:13\r\n    at Object.<anonymous> (C:\\Users\\jwilcurt\\AppData\\Roaming\\npm
\\node_modules\\npm\\bin\\npm-cli.js:76:3)\r\n' ]
```

Now NPM won't run properly:

```
C:\>npm --version
C:\Users\jwilcurt\AppData\Roaming\npm\node_modules\npm\lib\npm.js:18
  var fs = gfs.gracefulify(require('fs'))
               ^
TypeError: Object #<Object> has no method 'gracefulify'
    at C:\Users\jwilcurt\AppData\Roaming\npm\node_modules\npm\lib\npm.js:18:16
    at Object.<anonymous> (C:\Users\jwilcurt\AppData\Roaming\npm\node_modules\np
m\lib\npm.js:394:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at C:\Users\jwilcurt\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js:26:
13
    at Object.<anonymous> (C:\Users\jwilcurt\AppData\Roaming\npm\node_modules\np
m\bin\npm-cli.js:76:3)
C:\>
```

Also won't let me go back

```
C:\>npm-windows-upgrade
npm-windows-upgrade 0.3.2
? This tool will upgrade npm. Do you want to continue? Yes
We could not show latest available versions. Try running this script again with
the version you want to install (npm-windows-upgrade --version:3.0.0

C:\>npm-windows-upgrade --version 3.0.0
npm-windows-upgrade 0.3.2
? This tool will upgrade npm. Do you want to continue? Yes
We could not show latest available versions. Try running this script again with
the version you want to install (npm-windows-upgrade --version:3.0.0
```

**Comment by robertbaker** [comment]
To fix this, I would uninstall nodejs, and reinstall the version of node you want.
I would follow my nodejs clean uninstall instructions, found here https://github.com/felixrieseberg/npm-windows-upgrade#fix-an-attempted-upgrade

I don't think NPM 3.x is compatible with < 4.x of node.

You are using an old version of this package, once you reinstalled node, `npm i -g npm-windows-upgrade `

then update npm.

**Comment by felixrieseberg** [comment]
Yeah, @robertbaker is totally right here - npm 1 in particular is shockingly old and you'll very likely not have a good time. What seemed to have happened here is that you ended up with a Node/npm version mismatch, but there's sadly little we can do against that (given that we need npm to upgrade npm itself - once it's broken, we're lost...)
