### ISSUE TITLE
Error: Cannot find module babel-polyfill

### ISSUE THREAD

**Issue by Zazcallabah** [felixrieseberg/npm-windows-upgrade#82]
```
PS C:\src> npm install -g npm-windows-upgrade
C:\Users\peter.hamberg\AppData\Roaming\npm\npm-windows-upgrade -> C:\Users\peter.hamberg\AppData\Roaming\npm\node_module
s\npm-windows-upgrade\bin\npm-windows-upgrade.js
npm-windows-upgrade@3.0.2 C:\Users\peter.hamberg\AppData\Roaming\npm\node_modules\npm-windows-upgrade
├── cli-spinner@0.2.5
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── chalk@1.1.3 (supports-color@2.0.0, escape-string-regexp@1.0.5, ansi-styles@2.2.1, strip-ansi@3.0.1, has-ansi@2.0.0)
├── promise@7.1.1 (asap@2.0.4)
├── prompt@1.0.0 (revalidator@0.1.8, pkginfo@0.4.0, read@1.0.7, colors@1.1.2, winston@2.1.1, utile@0.3.0)
├── regenerator-runtime-only@0.8.38 (promise@6.1.0, es6-symbol@2.0.1)
└── inquirer@1.0.3 (ansi-escapes@1.4.0, mute-stream@0.0.6, through@2.3.8, strip-ansi@3.0.1, cli-width@2.1.0, pinkie-prom
ise@2.0.1, figures@1.7.0, run-async@2.2.0, string-width@1.0.1, cli-cursor@1.0.2, rx@4.1.0, lodash@4.13.1)
PS C:\src> npm-windows-upgrade
module.js:327
    throw err;
    ^

Error: Cannot find module 'babel-polyfill'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\peter.hamberg\AppData\Roaming\npm\node_modules\npm-windows-upgrade\bin\npm-windows-u
pgrade.js:3:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
 PS C:\src>

```

**Comment by felixrieseberg** [comment]
Thank you for the report - fixed and a new patch version released! If you try it again, it'll work :+1:
